import pandas as pd
df=pd.read_csv("E:\\Aishwarya_Python\\nyc_weather.csv")
print(df['Temperature'].max())
print(df['EST'][df['Events']=='Rain'])
df.fillna(0,inplace=True)
print(df['WindSpeedMPH'].mean())
print(df[2:5])
print(df.columns)
print(df.describe())
print([df['Temperature']>=32])
print(df.Temperature>=32)
print(df[['EST','Temperature']][df.Temperature==df['Temperature'].max()])
df.set_index('EST',inplace=True)
print(df.loc['1/4/2016'])
df.reset_index(inplace=True)
print(df)